### ISSUE TITLE
Scala 2.10

### ISSUE THREAD

**Issue by dirkgr** [softwaremill/scala-clippy#2]
On gitter, you asked me to create an issue for using Scala 2.10.

I don't actually use Scala 2.10. But sbt does. So I guess that's why I need this?

**Comment by amarouni** [comment]
Hello I'm getting this exception with 

Scala code runner version 2.11.7 -- Copyright 2002-2013, LAMP/EPFL

sbt 0.13

````java
Error:scalac: Error: org.jetbrains.jps.incremental.scala.remote.ServerException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at xsbt.CachedCompiler0$Compiler.superCall(CompilerInterface.scala:221)
	at xsbt.CachedCompiler0$Compiler.superComputePhaseDescriptors(CompilerInterface.scala:214)
	at xsbt.CachedCompiler0$Compiler.phaseDescriptors$lzycompute(CompilerInterface.scala:211)
	at xsbt.CachedCompiler0$Compiler.phaseDescriptors(CompilerInterface.scala:204)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1237)
	at xsbt.CachedCompiler0$$anon$2.<init>(CompilerInterface.scala:105)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:94)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:29)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:26)
	at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:67)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:24)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
Caused by: java.lang.NoClassDefFoundError: scala/xml/NodeSeq
	at com.softwaremill.clippy.ClippyPlugin.loadAdvices(ClippyPlugin.scala:87)
	at com.softwaremill.clippy.ClippyPlugin.init(ClippyPlugin.scala:26)
	at scala.tools.nsc.plugins.Plugins$$anonfun$loadPlugins$5.apply(Plugins.scala:99)
	at scala.tools.nsc.plugins.Plugins$$anonfun$loadPlugins$5.apply(Plugins.scala:99)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at scala.tools.nsc.plugins.Plugins$class.loadPlugins(Plugins.scala:99)
	at scala.tools.nsc.Global.loadPlugins(Global.scala:39)
	at scala.tools.nsc.plugins.Plugins$class.plugins(Plugins.scala:102)
	at scala.tools.nsc.Global.plugins$lzycompute(Global.scala:39)
	at scala.tools.nsc.Global.plugins(Global.scala:39)
	at scala.tools.nsc.plugins.Plugins$class.computePluginPhases(Plugins.scala:113)
	at scala.tools.nsc.Global.computePluginPhases(Global.scala:39)
	at scala.tools.nsc.Global.computePhaseDescriptors(Global.scala:750)
	... 30 more
Caused by: java.lang.ClassNotFoundException: scala.xml.NodeSeq
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more
````

**Comment by adamw** [comment]
I think that's resolved - please reopen if things still break
